name: lyricpro_app
description: Cross-platform Flutter client for LyricPro with local-first architecture.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.1.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^13.1.0
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.4
  drift: ^2.15.0
  drift_flutter: ^2.15.0
  sqlite3_flutter_libs: ^0.5.24
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  flutter_launcher_icons: ^0.14.1
  drift_dev: ^2.15.0
  json_serializable: ^6.7.1
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/LyricPro_icon.png



flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/LyricPro_icon.png
